// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: accounts.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts 
(
    country,
    deleted,
    nickname,
    owner_id
)
VALUES 
(
    $1,
    FALSE,
    $2,
    $3
)
RETURNING
    id,
    created_at,
    updated_at,
    country,
    nickname,
    owner_id
`

type CreateAccountParams struct {
	Country  Country
	Nickname sql.NullString
	OwnerID  uuid.NullUUID
}

type CreateAccountRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Country
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (CreateAccountRow, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Country, arg.Nickname, arg.OwnerID)
	var i CreateAccountRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.Nickname,
		&i.OwnerID,
	)
	return i, err
}

const deleteAccount = `-- name: DeleteAccount :exec

UPDATE accounts
SET
    updated_at = NOW(),
    deleted = TRUE
WHERE id = $1 AND owner_id = $2
`

type DeleteAccountParams struct {
	ID      uuid.UUID
	OwnerID uuid.NullUUID
}

func (q *Queries) DeleteAccount(ctx context.Context, arg DeleteAccountParams) error {
	_, err := q.db.Exec(ctx, deleteAccount, arg.ID, arg.OwnerID)
	return err
}

const getAccount = `-- name: GetAccount :one

SELECT
    id,
    created_at,
    updated_at,
    country,
    nickname,
    owner_id
FROM accounts
WHERE id = $1 AND owner_id = $2
`

type GetAccountParams struct {
	ID      uuid.UUID
	OwnerID uuid.NullUUID
}

type GetAccountRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Country
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (GetAccountRow, error) {
	row := q.db.QueryRow(ctx, getAccount, arg.ID, arg.OwnerID)
	var i GetAccountRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.Nickname,
		&i.OwnerID,
	)
	return i, err
}

const listAccountsByOwnerID = `-- name: ListAccountsByOwnerID :many

SELECT
    id,
    created_at,
    updated_at,
    country,
    nickname,
    owner_id
FROM accounts
WHERE owner_id = $1
ORDER BY created_at DESC
LIMIT COALESCE($2, 10)
`

type ListAccountsByOwnerIDParams struct {
	OwnerID uuid.NullUUID
	Limit   interface{}
}

type ListAccountsByOwnerIDRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Country
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

func (q *Queries) ListAccountsByOwnerID(ctx context.Context, arg ListAccountsByOwnerIDParams) ([]ListAccountsByOwnerIDRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByOwnerID, arg.OwnerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByOwnerIDRow
	for rows.Next() {
		var i ListAccountsByOwnerIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Country,
			&i.Nickname,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByUserID = `-- name: ListAccountsByUserID :many

SELECT
    accounts.id,
    accounts.created_at,
    accounts.updated_at,
    accounts.country,
    accounts.nickname,
    accounts.owner_id
FROM accounts
JOIN accounts_users 
ON accounts.id = accounts_users.account_id
WHERE accounts_users.user_id = $1
ORDER BY accounts.created_at DESC
LIMIT COALESCE($2, 10)
`

type ListAccountsByUserIDParams struct {
	UserID uuid.UUID
	Limit  interface{}
}

type ListAccountsByUserIDRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Country
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

func (q *Queries) ListAccountsByUserID(ctx context.Context, arg ListAccountsByUserIDParams) ([]ListAccountsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listAccountsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountsByUserIDRow
	for rows.Next() {
		var i ListAccountsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Country,
			&i.Nickname,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one

UPDATE accounts
SET
    updated_at = NOW(),
    country = COALESCE($1, country),
    nickname = COALESCE($2, nickname)
WHERE id = $3 AND owner_id = $4
RETURNING
    id,
    created_at,
    updated_at,
    country,
    nickname,
    owner_id
`

type UpdateAccountParams struct {
	Country  NullCountry
	Nickname sql.NullString
	ID       uuid.UUID
	OwnerID  uuid.NullUUID
}

type UpdateAccountRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Country
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (UpdateAccountRow, error) {
	row := q.db.QueryRow(ctx, updateAccount,
		arg.Country,
		arg.Nickname,
		arg.ID,
		arg.OwnerID,
	)
	var i UpdateAccountRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Country,
		&i.Nickname,
		&i.OwnerID,
	)
	return i, err
}
