// Code generated by sqlc.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys
(
    id,
    created_at,
    updated_at,
    expires_at,
    name,
    note,
    redacted_secret,
    secret,
    account_id
)
VALUES
(
    $1,
    $2::timestamp,
    $3::timestamp,
    COALESCE($4::timestamp, NULL),
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING
    id,
    created_at,
    updated_at,
    expires_at,
    name,
    note,
    redacted_secret
`

type CreateApiKeyParams struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      sql.NullTime
	Name           string
	RedactedSecret string
	Secret         string
	Note           sql.NullString
	ID             uuid.UUID
	AccountID      uuid.UUID
}

type CreateApiKeyRow struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      sql.NullTime
	Name           string
	RedactedSecret string
	Note           sql.NullString
	ID             uuid.UUID
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (CreateApiKeyRow, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.Name,
		arg.Note,
		arg.RedactedSecret,
		arg.Secret,
		arg.AccountID,
	)
	var i CreateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Name,
		&i.Note,
		&i.RedactedSecret,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec

DELETE FROM api_keys
WHERE id = $1 AND account_id = $1
`

func (q *Queries) DeleteApiKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiKey, id)
	return err
}

const expireApiKey = `-- name: ExpireApiKey :exec

UPDATE api_keys
SET
    updated_at = $1::timestamp,
    expires_at = $2::timestamp
WHERE id = $3 AND account_id = $4
`

type ExpireApiKeyParams struct {
	UpdatedAt time.Time
	ExpiresAt time.Time
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) ExpireApiKey(ctx context.Context, arg ExpireApiKeyParams) error {
	_, err := q.db.Exec(ctx, expireApiKey,
		arg.UpdatedAt,
		arg.ExpiresAt,
		arg.ID,
		arg.AccountID,
	)
	return err
}

const getApiKey = `-- name: GetApiKey :one

SELECT
    id,
    created_at,
    updated_at,
    expires_at,
    name,
    note,
    redacted_secret
FROM api_keys
WHERE id = $1 AND account_id = $2
`

type GetApiKeyParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetApiKeyRow struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      sql.NullTime
	Name           string
	RedactedSecret string
	Note           sql.NullString
	ID             uuid.UUID
}

func (q *Queries) GetApiKey(ctx context.Context, arg GetApiKeyParams) (GetApiKeyRow, error) {
	row := q.db.QueryRow(ctx, getApiKey, arg.ID, arg.AccountID)
	var i GetApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Name,
		&i.Note,
		&i.RedactedSecret,
	)
	return i, err
}

const getApiKeyAccAndExp = `-- name: GetApiKeyAccAndExp :one

SELECT
    expires_at,
    account_id
FROM api_keys
WHERE secret = $1
`

type GetApiKeyAccAndExpRow struct {
	ExpiresAt sql.NullTime
	AccountID uuid.UUID
}

func (q *Queries) GetApiKeyAccAndExp(ctx context.Context, secret string) (GetApiKeyAccAndExpRow, error) {
	row := q.db.QueryRow(ctx, getApiKeyAccAndExp, secret)
	var i GetApiKeyAccAndExpRow
	err := row.Scan(&i.ExpiresAt, &i.AccountID)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many

SELECT id, created_at, updated_at, expires_at, name, note, redacted_secret
FROM
(
    SELECT
        api_keys.id,
        api_keys.created_at,
        api_keys.updated_at,
        api_keys.expires_at,
        api_keys.name,
        api_keys.note,
        api_keys.redacted_secret
    FROM api_keys
    WHERE api_keys.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR api_keys.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR api_keys.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR api_keys.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR api_keys.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR api_keys.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR api_keys.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR api_keys.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR api_keys.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR $10::uuid > api_keys.id
        )
    AND 
        (
            $11::uuid IS NULL
            OR $11::uuid < api_keys.id
        )
    AND 
        (
            $12::text IS NULL 
            OR api_keys.name ~~* CONCAT('%', $12::text, '%')
        )
    ORDER BY 
    (
        CASE 
            WHEN $11::uuid IS NOT NULL 
            THEN api_keys.id
        END
    ) ASC,
    api_keys.id DESC
    LIMIT COALESCE($13::integer, 10) + 1
)
ORDER BY id DESC
`

type ListApiKeysParams struct {
	UpdatedAtLt   sql.NullTime
	CreatedAtGt   sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	UpdatedAtLte  sql.NullTime
	Name          sql.NullString
	Limit         sql.NullInt32
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	AccountID     uuid.UUID
}

type ListApiKeysRow struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      sql.NullTime
	Name           string
	RedactedSecret string
	Note           sql.NullString
	ID             uuid.UUID
}

func (q *Queries) ListApiKeys(ctx context.Context, arg ListApiKeysParams) ([]ListApiKeysRow, error) {
	rows, err := q.db.Query(ctx, listApiKeys,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApiKeysRow
	for rows.Next() {
		var i ListApiKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.Name,
			&i.Note,
			&i.RedactedSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApiKey = `-- name: UpdateApiKey :one

UPDATE api_keys
SET
    updated_at = $1::timestamp,
    name = COALESCE($2, name),
    note = COALESCE($3, note)
WHERE id = $4 AND account_id = $5
RETURNING
    id,
    created_at,
    updated_at,
    expires_at,
    name,
    note,
    redacted_secret
`

type UpdateApiKeyParams struct {
	UpdatedAt time.Time
	Name      sql.NullString
	Note      sql.NullString
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdateApiKeyRow struct {
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      sql.NullTime
	Name           string
	RedactedSecret string
	Note           sql.NullString
	ID             uuid.UUID
}

func (q *Queries) UpdateApiKey(ctx context.Context, arg UpdateApiKeyParams) (UpdateApiKeyRow, error) {
	row := q.db.QueryRow(ctx, updateApiKey,
		arg.UpdatedAt,
		arg.Name,
		arg.Note,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateApiKeyRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.Name,
		&i.Note,
		&i.RedactedSecret,
	)
	return i, err
}
