// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateItemVariantAttribute implements pgx.CopyFromSource.
type iteratorForCreateItemVariantAttribute struct {
	rows                 []CreateItemVariantAttributeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateItemVariantAttribute) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateItemVariantAttribute) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].AccountID,
		r.rows[0].ItemID,
	}, nil
}

func (r iteratorForCreateItemVariantAttribute) Err() error {
	return nil
}

func (q *Queries) CreateItemVariantAttribute(ctx context.Context, arg []CreateItemVariantAttributeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"item_variant_attributes"}, []string{"name", "account_id", "item_id"}, &iteratorForCreateItemVariantAttribute{rows: arg})
}

// iteratorForCreateItemVariantAttributeOption implements pgx.CopyFromSource.
type iteratorForCreateItemVariantAttributeOption struct {
	rows                 []CreateItemVariantAttributeOptionParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateItemVariantAttributeOption) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateItemVariantAttributeOption) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].AccountID,
		r.rows[0].ItemVariantAttributeID,
	}, nil
}

func (r iteratorForCreateItemVariantAttributeOption) Err() error {
	return nil
}

func (q *Queries) CreateItemVariantAttributeOption(ctx context.Context, arg []CreateItemVariantAttributeOptionParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"item_variant_attribute_options"}, []string{"name", "account_id", "item_variant_attribute_id"}, &iteratorForCreateItemVariantAttributeOption{rows: arg})
}

// iteratorForCreateItemVariants implements pgx.CopyFromSource.
type iteratorForCreateItemVariants struct {
	rows                 []CreateItemVariantsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateItemVariants) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateItemVariants) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Active,
		r.rows[0].Description,
		r.rows[0].Name,
		r.rows[0].PriceAmount,
		r.rows[0].PriceCurrency,
		r.rows[0].Type,
		r.rows[0].Variant,
		r.rows[0].AccountID,
		r.rows[0].GroupID,
		r.rows[0].InventoryID,
		r.rows[0].ParentItemID,
	}, nil
}

func (r iteratorForCreateItemVariants) Err() error {
	return nil
}

func (q *Queries) CreateItemVariants(ctx context.Context, arg []CreateItemVariantsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"items"}, []string{"active", "description", "name", "price_amount", "price_currency", "type", "variant", "account_id", "group_id", "inventory_id", "parent_item_id"}, &iteratorForCreateItemVariants{rows: arg})
}
