// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups 
(
    id,
    created_at,
    updated_at,
    description,
    name,
    account_id,
    parent_group_id
)
VALUES 
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_group_id
`

type CreateGroupParams struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	AccountID     uuid.UUID
	ParentGroupID uuid.NullUUID
}

type CreateGroupRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	ParentGroupID uuid.NullUUID
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (CreateGroupRow, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Description,
		arg.Name,
		arg.AccountID,
		arg.ParentGroupID,
	)
	var i CreateGroupRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Name,
		&i.ParentGroupID,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :exec

DELETE FROM groups
WHERE id = $1 AND account_id = $2
`

type DeleteGroupParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteGroup(ctx context.Context, arg DeleteGroupParams) error {
	_, err := q.db.Exec(ctx, deleteGroup, arg.ID, arg.AccountID)
	return err
}

const getGroup = `-- name: GetGroup :one

SELECT
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_group_id
FROM groups
WHERE id = $1 AND account_id = $2
`

type GetGroupParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetGroupRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	ParentGroupID uuid.NullUUID
}

func (q *Queries) GetGroup(ctx context.Context, arg GetGroupParams) (GetGroupRow, error) {
	row := q.db.QueryRow(ctx, getGroup, arg.ID, arg.AccountID)
	var i GetGroupRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Name,
		&i.ParentGroupID,
	)
	return i, err
}

const getGroupsByIDs = `-- name: GetGroupsByIDs :many

SELECT
	id,
	created_at,
	updated_at,
	description,
	name,
	parent_group_id
FROM groups
WHERE account_id = $1
    AND id = ANY($2::uuid[])
ORDER BY id DESC
`

type GetGroupsByIDsParams struct {
	AccountID uuid.UUID
	IDs       []uuid.UUID
}

type GetGroupsByIDsRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	ParentGroupID uuid.NullUUID
}

func (q *Queries) GetGroupsByIDs(ctx context.Context, arg GetGroupsByIDsParams) ([]GetGroupsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getGroupsByIDs, arg.AccountID, arg.IDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGroupsByIDsRow
	for rows.Next() {
		var i GetGroupsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.Name,
			&i.ParentGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many

SELECT id, created_at, updated_at, description, name, parent_group_id
FROM 
(
    SELECT
        groups.id,
        groups.created_at,
        groups.updated_at,
        groups.description,
        groups.name,
        groups.parent_group_id
    FROM groups
    WHERE groups.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR groups.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR groups.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR groups.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR groups.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR groups.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR groups.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR groups.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR groups.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR $10::uuid > groups.id
        )
    AND 
        (
            $11::uuid IS NULL
            OR $11::uuid < groups.id
        )
    AND 
        (
            $12::text IS NULL 
            OR groups.description ~~* CONCAT('%', $12::text, '%')
        )
    AND 
        (
            $13::text IS NULL 
            OR groups.name ~~* CONCAT('%', $13::text, '%')
        )
    AND 
        (
            $14::uuid IS NULL 
            OR groups.parent_group_id = $14::uuid
        )
    ORDER BY 
    (
        CASE 
            WHEN $11::uuid IS NOT NULL 
            THEN groups.id
        END
    ) ASC,
    groups.id DESC
    LIMIT COALESCE($15::integer, 10) + 1
)
ORDER BY id DESC
`

type ListGroupsParams struct {
	AccountID     uuid.UUID
	CreatedAtGt   sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	UpdatedAtLt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	UpdatedAtLte  sql.NullTime
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	Description   sql.NullString
	Name          sql.NullString
	ParentGroupID uuid.NullUUID
	Limit         sql.NullInt32
}

type ListGroupsRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	ParentGroupID uuid.NullUUID
}

func (q *Queries) ListGroups(ctx context.Context, arg ListGroupsParams) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.Description,
		arg.Name,
		arg.ParentGroupID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupsRow
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.Name,
			&i.ParentGroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one

UPDATE groups
SET
    updated_at = $1::timestamp,
    description = COALESCE($2, description),
    name = COALESCE($3, name),
    parent_group_id = COALESCE($4, parent_group_id)
WHERE id = $5 AND account_id = $6
RETURNING
    id,
    created_at,
    updated_at,
    description,
    name,
    parent_group_id
`

type UpdateGroupParams struct {
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          sql.NullString
	ParentGroupID uuid.NullUUID
	ID            uuid.UUID
	AccountID     uuid.UUID
}

type UpdateGroupRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	ParentGroupID uuid.NullUUID
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (UpdateGroupRow, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.UpdatedAt,
		arg.Description,
		arg.Name,
		arg.ParentGroupID,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateGroupRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Name,
		&i.ParentGroupID,
	)
	return i, err
}
