// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventories.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories 
(
    in_stock,
    orderable,
    account_id
)
VALUES 
(
    $1,
    $2,
    $3
)
RETURNING
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    reserved
`

type CreateInventoryParams struct {
	InStock   int32
	Orderable sql.NullInt32
	AccountID uuid.UUID
}

type CreateInventoryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (CreateInventoryRow, error) {
	row := q.db.QueryRow(ctx, createInventory, arg.InStock, arg.Orderable, arg.AccountID)
	var i CreateInventoryRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InStock,
		&i.Orderable,
		&i.Reserved,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec

DELETE FROM inventories
WHERE id = $1 AND account_id = $2
`

type DeleteInventoryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteInventory(ctx context.Context, arg DeleteInventoryParams) error {
	_, err := q.db.Exec(ctx, deleteInventory, arg.ID, arg.AccountID)
	return err
}

const getInventory = `-- name: GetInventory :one

SELECT
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    reserved
FROM inventories
WHERE id = $1 AND account_id = $2
`

type GetInventoryParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetInventoryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
}

func (q *Queries) GetInventory(ctx context.Context, arg GetInventoryParams) (GetInventoryRow, error) {
	row := q.db.QueryRow(ctx, getInventory, arg.ID, arg.AccountID)
	var i GetInventoryRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InStock,
		&i.Orderable,
		&i.Reserved,
	)
	return i, err
}

const listInventories = `-- name: ListInventories :many

SELECT id, created_at, updated_at, in_stock, orderable, reserved
FROM
(
    SELECT
        inventories.id,
        inventories.created_at,
        inventories.updated_at,
        inventories.in_stock,
        inventories.orderable,
        inventories.reserved
    FROM inventories
    WHERE inventories.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR inventories.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR inventories.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR inventories.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR inventories.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR inventories.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR inventories.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR inventories.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR inventories.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR 
            (
                (
                    $11::timestamp,
                    $10::uuid
                ) > (inventories.created_at, inventories.id)
            )
        )
    AND 
        (
            $12::uuid IS NULL
            OR 
            (
                (
                    $13::timestamp,
                    $12::uuid
                ) < (inventories.created_at, inventories.id)
            )
        )
    AND
        (
            $14::integer IS NULL 
            OR inventories.in_stock > $14::integer
        )
    AND 
        (
            $15::integer IS NULL 
            OR inventories.in_stock < $15::integer
        )
    AND 
        (
            $16::integer IS NULL 
            OR inventories.in_stock >= $16::integer
        )
    AND 
        (
            $17::integer IS NULL 
            OR inventories.in_stock <= $17::integer
        )
    AND
        (
            $18::integer IS NULL 
            OR inventories.orderable > $18::integer
        )
    AND 
        (
            $19::integer IS NULL 
            OR inventories.orderable < $19::integer
        )
    AND 
        (
            $20::integer IS NULL 
            OR inventories.orderable >= $20::integer
        )
    AND 
        (
            $21::integer IS NULL 
            OR inventories.orderable <= $21::integer
        )
    AND
        (
            $22::integer IS NULL 
            OR inventories.reserved > $22::integer
        )
    AND 
        (
            $23::integer IS NULL 
            OR inventories.reserved < $23::integer
        )
    AND 
        (
            $24::integer IS NULL 
            OR inventories.reserved >= $24::integer
        )
    AND 
        (
            $25::integer IS NULL 
            OR inventories.reserved <= $25::integer
        )
    ORDER BY 
    (
        CASE 
            WHEN $12::uuid IS NOT NULL 
            THEN (inventories.created_at, inventories.id)
        END
    ) ASC,
    (inventories.created_at, inventories.id) DESC
    LIMIT COALESCE($26::integer, 10) + 1
)
ORDER BY created_at DESC, id DESC
`

type ListInventoriesParams struct {
	AccountID         uuid.UUID
	CreatedAtGt       sql.NullTime
	CreatedAtLt       sql.NullTime
	CreatedAtGte      sql.NullTime
	CreatedAtLte      sql.NullTime
	UpdatedAtGt       sql.NullTime
	UpdatedAtLt       sql.NullTime
	UpdatedAtGte      sql.NullTime
	UpdatedAtLte      sql.NullTime
	StartingAfter     uuid.NullUUID
	StartingAfterDate sql.NullTime
	EndingBefore      uuid.NullUUID
	EndingBeforeDate  sql.NullTime
	InStockGt         sql.NullInt32
	InStockLt         sql.NullInt32
	InStockGte        sql.NullInt32
	InStockLte        sql.NullInt32
	OrderableGt       sql.NullInt32
	OrderableLt       sql.NullInt32
	OrderableGte      sql.NullInt32
	OrderableLte      sql.NullInt32
	ReservedGt        sql.NullInt32
	ReservedLt        sql.NullInt32
	ReservedGte       sql.NullInt32
	ReservedLte       sql.NullInt32
	Limit             sql.NullInt32
}

type ListInventoriesRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
}

func (q *Queries) ListInventories(ctx context.Context, arg ListInventoriesParams) ([]ListInventoriesRow, error) {
	rows, err := q.db.Query(ctx, listInventories,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.StartingAfterDate,
		arg.EndingBefore,
		arg.EndingBeforeDate,
		arg.InStockGt,
		arg.InStockLt,
		arg.InStockGte,
		arg.InStockLte,
		arg.OrderableGt,
		arg.OrderableLt,
		arg.OrderableGte,
		arg.OrderableLte,
		arg.ReservedGt,
		arg.ReservedLt,
		arg.ReservedGte,
		arg.ReservedLte,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoriesRow
	for rows.Next() {
		var i ListInventoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InStock,
			&i.Orderable,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoriesByIds = `-- name: ListInventoriesByIds :many

SELECT
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    reserved
FROM inventories
WHERE account_id = $1
    AND id = ANY($2::uuid[])
ORDER BY created_at DESC, id DESC
`

type ListInventoriesByIdsParams struct {
	AccountID uuid.UUID
	Ids       []uuid.UUID
}

type ListInventoriesByIdsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
}

func (q *Queries) ListInventoriesByIds(ctx context.Context, arg ListInventoriesByIdsParams) ([]ListInventoriesByIdsRow, error) {
	rows, err := q.db.Query(ctx, listInventoriesByIds, arg.AccountID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoriesByIdsRow
	for rows.Next() {
		var i ListInventoriesByIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InStock,
			&i.Orderable,
			&i.Reserved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :one

UPDATE inventories
SET
    updated_at = $1::timestamp,
    in_stock = COALESCE($2, in_stock),
    orderable = COALESCE($3, orderable),
    reserved = COALESCE($4, reserved)
WHERE id = $5 AND account_id = $6
RETURNING
    id,
    created_at,
    updated_at,
    in_stock,
    orderable,
    reserved
`

type UpdateInventoryParams struct {
	UpdatedAt time.Time
	InStock   sql.NullInt32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdateInventoryRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) (UpdateInventoryRow, error) {
	row := q.db.QueryRow(ctx, updateInventory,
		arg.UpdatedAt,
		arg.InStock,
		arg.Orderable,
		arg.Reserved,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateInventoryRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InStock,
		&i.Orderable,
		&i.Reserved,
	)
	return i, err
}
