// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_movements.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements
(
    type,     
    account_id,
    inventory_id,
    item_id
)
VALUES 
(
    $1,
    $2,
    $3,
    $4
)
RETURNING
    id,
    created_at,
    updated_at,
    inventory_id,
    item_id,
    type
`

type CreateInventoryMovementParams struct {
	Type        InventoryMovementType
	AccountID   uuid.UUID
	InventoryID uuid.UUID
	ItemID      uuid.UUID
}

type CreateInventoryMovementRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	InventoryID uuid.UUID
	ItemID      uuid.UUID
	Type        InventoryMovementType
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (CreateInventoryMovementRow, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.Type,
		arg.AccountID,
		arg.InventoryID,
		arg.ItemID,
	)
	var i CreateInventoryMovementRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryID,
		&i.ItemID,
		&i.Type,
	)
	return i, err
}

const getInventoryMovement = `-- name: GetInventoryMovement :one

SELECT
    inventory_movements.id,
    inventory_movements.created_at,
    inventory_movements.updated_at,
    inventory_movements.inventory_id,
    inventory_movements.item_id,
    inventory_movement_references.id AS inventory_movement_reference_id,
    inventory_movements.type
FROM inventory_movements
LEFT JOIN inventory_movement_references ON inventory_movements.id = inventory_movement_references.inventory_movement_id
WHERE inventory_movements.id = $1 AND inventory_movements.account_id = $2
`

type GetInventoryMovementParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetInventoryMovementRow struct {
	ID                           uuid.UUID
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	InventoryID                  uuid.UUID
	ItemID                       uuid.UUID
	InventoryMovementReferenceID uuid.NullUUID
	Type                         InventoryMovementType
}

func (q *Queries) GetInventoryMovement(ctx context.Context, arg GetInventoryMovementParams) (GetInventoryMovementRow, error) {
	row := q.db.QueryRow(ctx, getInventoryMovement, arg.ID, arg.AccountID)
	var i GetInventoryMovementRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryID,
		&i.ItemID,
		&i.InventoryMovementReferenceID,
		&i.Type,
	)
	return i, err
}

const listInventoryMovements = `-- name: ListInventoryMovements :many

SELECT id, created_at, updated_at, inventory_id, item_id, inventory_movement_reference_id, type
FROM 
(
    SELECT
        inventory_movements.id,
        inventory_movements.created_at,
        inventory_movements.updated_at,
        inventory_movements.inventory_id,
        inventory_movements.item_id,
        inventory_movement_references.id AS inventory_movement_reference_id,
        inventory_movements.type
    FROM inventory_movements
    LEFT JOIN inventory_movement_references ON inventory_movements.id = inventory_movement_references.inventory_movement_id
    WHERE inventory_movements.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR inventory_movements.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR inventory_movements.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR inventory_movements.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR inventory_movements.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR inventory_movements.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR inventory_movements.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR inventory_movements.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR inventory_movements.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR 
            (
                (
                    $11::timestamp,
                    $10::uuid
                ) > (inventory_movements.created_at, inventory_movements.id)
            )
        )
    AND 
        (
            $12::uuid IS NULL
            OR 
            (
                (
                    $13::timestamp,
                    $12::uuid
                ) < (inventory_movements.created_at, inventory_movements.id)
            )
        )
    AND 
        (
            $14::uuid IS NULL 
            OR inventory_movements.item_id = $14::uuid
        )
    AND 
        (
            $15::uuid IS NULL 
            OR inventory_movements.inventory_id = $15::uuid
        )
    AND 
        (
            $16::inventory_movement_type IS NULL 
            OR inventory_movements.type = $16::inventory_movement_type
        )
    ORDER BY 
    (
        CASE 
            WHEN $12::uuid IS NOT NULL 
            THEN (inventory_movements.created_at, inventory_movements.id)
        END
    ) ASC,
    (inventory_movements.created_at, inventory_movements.id) DESC
    LIMIT COALESCE($17::integer, 10) + 1
)
ORDER BY created_at DESC, id DESC
`

type ListInventoryMovementsParams struct {
	AccountID         uuid.UUID
	CreatedAtGt       sql.NullTime
	CreatedAtLt       sql.NullTime
	CreatedAtGte      sql.NullTime
	CreatedAtLte      sql.NullTime
	UpdatedAtGt       sql.NullTime
	UpdatedAtLt       sql.NullTime
	UpdatedAtGte      sql.NullTime
	UpdatedAtLte      sql.NullTime
	StartingAfter     uuid.NullUUID
	StartingAfterDate sql.NullTime
	EndingBefore      uuid.NullUUID
	EndingBeforeDate  sql.NullTime
	ItemID            uuid.NullUUID
	InventoryID       uuid.NullUUID
	Type              NullInventoryMovementType
	Limit             sql.NullInt32
}

type ListInventoryMovementsRow struct {
	ID                           uuid.UUID
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	InventoryID                  uuid.UUID
	ItemID                       uuid.UUID
	InventoryMovementReferenceID uuid.NullUUID
	Type                         InventoryMovementType
}

func (q *Queries) ListInventoryMovements(ctx context.Context, arg ListInventoryMovementsParams) ([]ListInventoryMovementsRow, error) {
	rows, err := q.db.Query(ctx, listInventoryMovements,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.StartingAfterDate,
		arg.EndingBefore,
		arg.EndingBeforeDate,
		arg.ItemID,
		arg.InventoryID,
		arg.Type,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryMovementsRow
	for rows.Next() {
		var i ListInventoryMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryID,
			&i.ItemID,
			&i.InventoryMovementReferenceID,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
