// Code generated by sqlc.
// versions:
//   sqlc v1.30.0
// source: inventory_movements.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements
(
    id,
    created_at,
    updated_at,
    type,     
    account_id,
    inventory_id,
    item_id
)
VALUES 
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    created_at,
    updated_at,
    inventory_id,
    item_id,
    type
`

type CreateInventoryMovementParams struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Type        InventoryMovementType
	ID          uuid.UUID
	AccountID   uuid.UUID
	InventoryID uuid.UUID
	ItemID      uuid.UUID
}

type CreateInventoryMovementRow struct {
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Type        InventoryMovementType
	ID          uuid.UUID
	InventoryID uuid.UUID
	ItemID      uuid.UUID
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (CreateInventoryMovementRow, error) {
	row := q.db.QueryRow(ctx, createInventoryMovement,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
		arg.AccountID,
		arg.InventoryID,
		arg.ItemID,
	)
	var i CreateInventoryMovementRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryID,
		&i.ItemID,
		&i.Type,
	)
	return i, err
}

const getInventoryMovement = `-- name: GetInventoryMovement :one

SELECT
    inventory_movements.id,
    inventory_movements.created_at,
    inventory_movements.updated_at,
    inventory_movements.inventory_id,
    inventory_movements.item_id,
    inventory_movement_references.id AS inventory_movement_reference_id,
    inventory_movements.type
FROM inventory_movements
LEFT JOIN inventory_movement_references ON inventory_movements.id = inventory_movement_references.inventory_movement_id
WHERE inventory_movements.id = $1 AND inventory_movements.account_id = $2
`

type GetInventoryMovementParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetInventoryMovementRow struct {
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	Type                         InventoryMovementType
	InventoryMovementReferenceID uuid.NullUUID
	ID                           uuid.UUID
	InventoryID                  uuid.UUID
	ItemID                       uuid.UUID
}

func (q *Queries) GetInventoryMovement(ctx context.Context, arg GetInventoryMovementParams) (GetInventoryMovementRow, error) {
	row := q.db.QueryRow(ctx, getInventoryMovement, arg.ID, arg.AccountID)
	var i GetInventoryMovementRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryID,
		&i.ItemID,
		&i.InventoryMovementReferenceID,
		&i.Type,
	)
	return i, err
}

const listInventoryMovements = `-- name: ListInventoryMovements :many

SELECT id, created_at, updated_at, inventory_id, item_id, inventory_movement_reference_id, type
FROM 
(
    SELECT
        inventory_movements.id,
        inventory_movements.created_at,
        inventory_movements.updated_at,
        inventory_movements.inventory_id,
        inventory_movements.item_id,
        inventory_movement_references.id AS inventory_movement_reference_id,
        inventory_movements.type
    FROM inventory_movements
    LEFT JOIN inventory_movement_references ON inventory_movements.id = inventory_movement_references.inventory_movement_id
    WHERE inventory_movements.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR inventory_movements.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR inventory_movements.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR inventory_movements.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR inventory_movements.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR inventory_movements.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR inventory_movements.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR inventory_movements.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR inventory_movements.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR $10::uuid > inventory_movements.id
        )
    AND 
        (
            $11::uuid IS NULL
            OR $11::uuid < inventory_movements.id
        )
    AND 
        (
            $12::uuid IS NULL 
            OR inventory_movements.item_id = $12::uuid
        )
    AND 
        (
            $13::uuid IS NULL 
            OR inventory_movements.inventory_id = $13::uuid
        )
    AND 
        (
            $14::inventory_movement_type IS NULL 
            OR inventory_movements.type = $14::inventory_movement_type
        )
    ORDER BY 
    (
        CASE 
            WHEN $11::uuid IS NOT NULL 
            THEN inventory_movements.id
        END
    ) ASC,
    inventory_movements.id DESC
    LIMIT COALESCE($15::integer, 10) + 1
)
ORDER BY id DESC
`

type ListInventoryMovementsParams struct {
	UpdatedAtLt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	CreatedAtGt   sql.NullTime
	UpdatedAtLte  sql.NullTime
	Type          NullInventoryMovementType
	Limit         sql.NullInt32
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	ItemID        uuid.NullUUID
	InventoryID   uuid.NullUUID
	AccountID     uuid.UUID
}

type ListInventoryMovementsRow struct {
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	Type                         InventoryMovementType
	InventoryMovementReferenceID uuid.NullUUID
	ID                           uuid.UUID
	InventoryID                  uuid.UUID
	ItemID                       uuid.UUID
}

func (q *Queries) ListInventoryMovements(ctx context.Context, arg ListInventoryMovementsParams) ([]ListInventoryMovementsRow, error) {
	rows, err := q.db.Query(ctx, listInventoryMovements,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.ItemID,
		arg.InventoryID,
		arg.Type,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryMovementsRow
	for rows.Next() {
		var i ListInventoryMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryID,
			&i.ItemID,
			&i.InventoryMovementReferenceID,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
