// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory_movement_references.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createInventoryMovementReference = `-- name: CreateInventoryMovementReference :one
INSERT INTO inventory_movement_references 
(
    id,
    created_at,
    updated_at,
    type,  
    value,
    account_id,
    inventory_movement_id
)
VALUES 
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING
    id,
    created_at,
    updated_at,
    inventory_movement_id,
    type,
    value,
    account_id
`

type CreateInventoryMovementReferenceParams struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Type                InventoryMovementReferenceType
	Value               string
	AccountID           uuid.UUID
	InventoryMovementID uuid.UUID
}

type CreateInventoryMovementReferenceRow struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	InventoryMovementID uuid.UUID
	Type                InventoryMovementReferenceType
	Value               string
	AccountID           uuid.UUID
}

func (q *Queries) CreateInventoryMovementReference(ctx context.Context, arg CreateInventoryMovementReferenceParams) (CreateInventoryMovementReferenceRow, error) {
	row := q.db.QueryRow(ctx, createInventoryMovementReference,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Type,
		arg.Value,
		arg.AccountID,
		arg.InventoryMovementID,
	)
	var i CreateInventoryMovementReferenceRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.InventoryMovementID,
		&i.Type,
		&i.Value,
		&i.AccountID,
	)
	return i, err
}

const getInventoryMovementReference = `-- name: GetInventoryMovementReference :many

SELECT
    id,
    created_at,
    updated_at,
    inventory_movement_id,
    type,
    value
FROM inventory_movement_references
WHERE id = $1 AND account_id = $2
`

type GetInventoryMovementReferenceParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetInventoryMovementReferenceRow struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	InventoryMovementID uuid.UUID
	Type                InventoryMovementReferenceType
	Value               string
}

func (q *Queries) GetInventoryMovementReference(ctx context.Context, arg GetInventoryMovementReferenceParams) ([]GetInventoryMovementReferenceRow, error) {
	rows, err := q.db.Query(ctx, getInventoryMovementReference, arg.ID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryMovementReferenceRow
	for rows.Next() {
		var i GetInventoryMovementReferenceRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryMovementID,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryMovementReferences = `-- name: ListInventoryMovementReferences :many

SELECT id, created_at, updated_at, inventory_movement_id, type, value
FROM 
(
    SELECT
        inventory_movement_references.id,
        inventory_movement_references.created_at,
        inventory_movement_references.updated_at,
        inventory_movement_references.inventory_movement_id,
        inventory_movement_references.type,
        inventory_movement_references.value
    FROM inventory_movement_references
    WHERE inventory_movement_references.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR inventory_movement_references.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR inventory_movement_references.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR inventory_movement_references.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR inventory_movement_references.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR inventory_movement_references.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR inventory_movement_references.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR inventory_movement_references.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR inventory_movement_references.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR $10::uuid > inventory_movement_references.id
        )
    AND 
        (
            $11::uuid IS NULL
            OR $11::uuid < inventory_movement_references.id
        )
    AND 
        (
            $12::uuid IS NULL 
            OR inventory_movement_references.inventory_movement_id = $12::uuid
        )
    AND 
        (
            $13::inventory_movement_reference_type IS NULL 
            OR inventory_movement_references.type = $13::inventory_movement_reference_type
        )
    AND 
        (
            $14::text IS NULL 
            OR inventory_movement_references.value ~~* CONCAT('%', $14::text, '%')
        )
    ORDER BY 
    (
        CASE 
            WHEN $11::uuid IS NOT NULL 
            THEN inventory_movement_references.id
        END
    ) ASC,
    (inventory_movement_references.created_at, inventory_movement_references.id) DESC
    LIMIT COALESCE($15::integer, 10) + 1
)
ORDER BY id DESC
`

type ListInventoryMovementReferencesParams struct {
	AccountID           uuid.UUID
	CreatedAtGt         sql.NullTime
	CreatedAtLt         sql.NullTime
	CreatedAtGte        sql.NullTime
	CreatedAtLte        sql.NullTime
	UpdatedAtGt         sql.NullTime
	UpdatedAtLt         sql.NullTime
	UpdatedAtGte        sql.NullTime
	UpdatedAtLte        sql.NullTime
	StartingAfter       uuid.NullUUID
	EndingBefore        uuid.NullUUID
	InventoryMovementID uuid.NullUUID
	Type                NullInventoryMovementReferenceType
	Value               sql.NullString
	Limit               sql.NullInt32
}

type ListInventoryMovementReferencesRow struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	InventoryMovementID uuid.UUID
	Type                InventoryMovementReferenceType
	Value               string
}

func (q *Queries) ListInventoryMovementReferences(ctx context.Context, arg ListInventoryMovementReferencesParams) ([]ListInventoryMovementReferencesRow, error) {
	rows, err := q.db.Query(ctx, listInventoryMovementReferences,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.InventoryMovementID,
		arg.Type,
		arg.Value,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryMovementReferencesRow
	for rows.Next() {
		var i ListInventoryMovementReferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.InventoryMovementID,
			&i.Type,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
