// Code generated by sqlc.
// versions:
//   sqlc v1.30.0
// source: item_variant_attribute_options.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CreateItemVariantAttributeOptionParams struct {
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	ID                     uuid.UUID
	AccountID              uuid.UUID
	ItemVariantAttributeID uuid.UUID
}

const deleteItemVariantAttributeOption = `-- name: DeleteItemVariantAttributeOption :exec

DELETE FROM item_variant_attribute_options
WHERE id = $1 AND account_id = $2
`

type DeleteItemVariantAttributeOptionParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteItemVariantAttributeOption(ctx context.Context, arg DeleteItemVariantAttributeOptionParams) error {
	_, err := q.db.Exec(ctx, deleteItemVariantAttributeOption, arg.ID, arg.AccountID)
	return err
}

const getItemVariantAttributeOption = `-- name: GetItemVariantAttributeOption :one

SELECT
    id,
    created_at,
    updated_at,
    name,
    item_variant_attribute_id
FROM item_variant_attribute_options
WHERE id = $1 AND account_id = $2
`

type GetItemVariantAttributeOptionParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetItemVariantAttributeOptionRow struct {
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	ID                     uuid.UUID
	ItemVariantAttributeID uuid.UUID
}

func (q *Queries) GetItemVariantAttributeOption(ctx context.Context, arg GetItemVariantAttributeOptionParams) (GetItemVariantAttributeOptionRow, error) {
	row := q.db.QueryRow(ctx, getItemVariantAttributeOption, arg.ID, arg.AccountID)
	var i GetItemVariantAttributeOptionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ItemVariantAttributeID,
	)
	return i, err
}

const listItemVariantAttributeOptions = `-- name: ListItemVariantAttributeOptions :many

SELECT id, created_at, updated_at, name, item_variant_attribute_id
FROM
(
    SELECT
        item_variant_attribute_options.id,
        item_variant_attribute_options.created_at,
        item_variant_attribute_options.updated_at,
        item_variant_attribute_options.name,
        item_variant_attribute_options.item_variant_attribute_id
    FROM item_variant_attribute_options
    WHERE item_variant_attribute_options.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR item_variant_attribute_options.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR item_variant_attribute_options.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR item_variant_attribute_options.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR item_variant_attribute_options.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR item_variant_attribute_options.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR item_variant_attribute_options.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR item_variant_attribute_options.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR item_variant_attribute_options.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR $10::uuid > item_variant_attribute_options.id
        )
    AND 
        (
            $11::uuid IS NULL
            OR $11::uuid < item_variant_attribute_options.id
        )
    AND 
        (
            $12::text IS NULL 
            OR item_variant_attribute_options.name ~~* CONCAT('%', $12::text, '%')
        )
    ORDER BY 
    (
        CASE 
            WHEN $11::uuid IS NOT NULL 
            THEN item_variant_attribute_options.id
        END
    ) ASC,
    item_variant_attribute_options.id DESC
    LIMIT COALESCE($13::integer, 10) + 1
)
ORDER BY id DESC
`

type ListItemVariantAttributeOptionsParams struct {
	UpdatedAtLt   sql.NullTime
	CreatedAtGt   sql.NullTime
	CreatedAtLt   sql.NullTime
	CreatedAtGte  sql.NullTime
	CreatedAtLte  sql.NullTime
	UpdatedAtGt   sql.NullTime
	UpdatedAtGte  sql.NullTime
	UpdatedAtLte  sql.NullTime
	Name          sql.NullString
	Limit         sql.NullInt32
	StartingAfter uuid.NullUUID
	EndingBefore  uuid.NullUUID
	AccountID     uuid.UUID
}

type ListItemVariantAttributeOptionsRow struct {
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	ID                     uuid.UUID
	ItemVariantAttributeID uuid.UUID
}

func (q *Queries) ListItemVariantAttributeOptions(ctx context.Context, arg ListItemVariantAttributeOptionsParams) ([]ListItemVariantAttributeOptionsRow, error) {
	rows, err := q.db.Query(ctx, listItemVariantAttributeOptions,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.EndingBefore,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemVariantAttributeOptionsRow
	for rows.Next() {
		var i ListItemVariantAttributeOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ItemVariantAttributeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemVariantAttributeOption = `-- name: UpdateItemVariantAttributeOption :one

UPDATE item_variant_attribute_options
SET
    updated_at = $1::timestamp,
    name = COALESCE($2, name)
WHERE id = $3 AND account_id = $4
RETURNING
    id,
    created_at,
    updated_at,
    name,
    item_variant_attribute_id
`

type UpdateItemVariantAttributeOptionParams struct {
	UpdatedAt time.Time
	Name      sql.NullString
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdateItemVariantAttributeOptionRow struct {
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	ID                     uuid.UUID
	ItemVariantAttributeID uuid.UUID
}

func (q *Queries) UpdateItemVariantAttributeOption(ctx context.Context, arg UpdateItemVariantAttributeOptionParams) (UpdateItemVariantAttributeOptionRow, error) {
	row := q.db.QueryRow(ctx, updateItemVariantAttributeOption,
		arg.UpdatedAt,
		arg.Name,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateItemVariantAttributeOptionRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ItemVariantAttributeID,
	)
	return i, err
}
