// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_identifiers.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createItemIdentifier = `-- name: CreateItemIdentifier :one
INSERT INTO item_identifiers 
(
    ean,
    gtin,
    isbn,
    jan,
    mpn,
    nsn,
    upc,
    qr,
    sku,
    account_id,
    item_id
)
VALUES 
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
RETURNING
    id,
    created_at,
    updated_at,
    ean,
    gtin,
    isbn,
    jan,
    mpn,
    nsn,
    upc,
    qr,
    sku,
    item_id
`

type CreateItemIdentifierParams struct {
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type CreateItemIdentifierRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	ItemID    uuid.UUID
}

func (q *Queries) CreateItemIdentifier(ctx context.Context, arg CreateItemIdentifierParams) (CreateItemIdentifierRow, error) {
	row := q.db.QueryRow(ctx, createItemIdentifier,
		arg.Ean,
		arg.Gtin,
		arg.Isbn,
		arg.Jan,
		arg.Mpn,
		arg.Nsn,
		arg.Upc,
		arg.Qr,
		arg.Sku,
		arg.AccountID,
		arg.ItemID,
	)
	var i CreateItemIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ean,
		&i.Gtin,
		&i.Isbn,
		&i.Jan,
		&i.Mpn,
		&i.Nsn,
		&i.Upc,
		&i.Qr,
		&i.Sku,
		&i.ItemID,
	)
	return i, err
}

const deleteItemIdentifier = `-- name: DeleteItemIdentifier :exec

DELETE FROM item_identifiers
WHERE id = $1 AND account_id = $2
`

type DeleteItemIdentifierParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteItemIdentifier(ctx context.Context, arg DeleteItemIdentifierParams) error {
	_, err := q.db.Exec(ctx, deleteItemIdentifier, arg.ID, arg.AccountID)
	return err
}

const getItemIdentifier = `-- name: GetItemIdentifier :one

SELECT
    id,
    created_at,
    updated_at,
    ean,
    gtin,
    isbn,
    jan,
    mpn,
    nsn,
    upc,
    qr,
    sku,
    item_id
FROM item_identifiers
WHERE id = $1 AND account_id = $2
`

type GetItemIdentifierParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetItemIdentifierRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	ItemID    uuid.UUID
}

func (q *Queries) GetItemIdentifier(ctx context.Context, arg GetItemIdentifierParams) (GetItemIdentifierRow, error) {
	row := q.db.QueryRow(ctx, getItemIdentifier, arg.ID, arg.AccountID)
	var i GetItemIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ean,
		&i.Gtin,
		&i.Isbn,
		&i.Jan,
		&i.Mpn,
		&i.Nsn,
		&i.Upc,
		&i.Qr,
		&i.Sku,
		&i.ItemID,
	)
	return i, err
}

const listItemIdentifiers = `-- name: ListItemIdentifiers :many

SELECT id, created_at, updated_at, ean, gtin, isbn, jan, mpn, nsn, upc, qr, sku, item_id
FROM
(
    SELECT
        item_identifiers.id,
        item_identifiers.created_at,
        item_identifiers.updated_at,
        item_identifiers.ean,
        item_identifiers.gtin,
        item_identifiers.isbn,
        item_identifiers.jan,
        item_identifiers.mpn,
        item_identifiers.nsn,
        item_identifiers.upc,
        item_identifiers.qr,
        item_identifiers.sku,
        item_identifiers.item_id
    FROM item_identifiers
    WHERE item_identifiers.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR item_identifiers.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR item_identifiers.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR item_identifiers.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR item_identifiers.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR item_identifiers.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR item_identifiers.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR item_identifiers.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR item_identifiers.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR 
            (
                (
                    $11::timestamp,
                    $10::uuid
                ) > (item_identifiers.created_at, item_identifiers.id)
            )
        )
    AND 
        (
            $12::uuid IS NULL
            OR 
            (
                (
                    $13::timestamp,
                    $12::uuid
                ) < (item_identifiers.created_at, item_identifiers.id)
            )
        )
    ORDER BY 
    (
        CASE 
            WHEN $12::uuid IS NOT NULL 
            THEN (item_identifiers.created_at, item_identifiers.id)
        END
    ) ASC,
    (item_identifiers.created_at, item_identifiers.id) DESC
    LIMIT COALESCE($14::integer, 10) + 1
)
ORDER BY created_at DESC, id DESC
`

type ListItemIdentifiersParams struct {
	AccountID         uuid.UUID
	CreatedAtGt       sql.NullTime
	CreatedAtLt       sql.NullTime
	CreatedAtGte      sql.NullTime
	CreatedAtLte      sql.NullTime
	UpdatedAtGt       sql.NullTime
	UpdatedAtLt       sql.NullTime
	UpdatedAtGte      sql.NullTime
	UpdatedAtLte      sql.NullTime
	StartingAfter     uuid.NullUUID
	StartingAfterDate sql.NullTime
	EndingBefore      uuid.NullUUID
	EndingBeforeDate  sql.NullTime
	Limit             sql.NullInt32
}

type ListItemIdentifiersRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	ItemID    uuid.UUID
}

func (q *Queries) ListItemIdentifiers(ctx context.Context, arg ListItemIdentifiersParams) ([]ListItemIdentifiersRow, error) {
	rows, err := q.db.Query(ctx, listItemIdentifiers,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.StartingAfterDate,
		arg.EndingBefore,
		arg.EndingBeforeDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemIdentifiersRow
	for rows.Next() {
		var i ListItemIdentifiersRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ean,
			&i.Gtin,
			&i.Isbn,
			&i.Jan,
			&i.Mpn,
			&i.Nsn,
			&i.Upc,
			&i.Qr,
			&i.Sku,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemIdentifiersByIds = `-- name: ListItemIdentifiersByIds :many

SELECT
	id,
    created_at,
    updated_at,
    ean,
    gtin,
    isbn,
    jan,
    mpn,
    nsn,
    upc,
    qr,
    sku,
    item_id
FROM item_identifiers
WHERE account_id = $1
    AND id = ANY($2::uuid[])
ORDER BY created_at DESC, id DESC
`

type ListItemIdentifiersByIdsParams struct {
	AccountID uuid.UUID
	Ids       []uuid.UUID
}

type ListItemIdentifiersByIdsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	ItemID    uuid.UUID
}

func (q *Queries) ListItemIdentifiersByIds(ctx context.Context, arg ListItemIdentifiersByIdsParams) ([]ListItemIdentifiersByIdsRow, error) {
	rows, err := q.db.Query(ctx, listItemIdentifiersByIds, arg.AccountID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemIdentifiersByIdsRow
	for rows.Next() {
		var i ListItemIdentifiersByIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Ean,
			&i.Gtin,
			&i.Isbn,
			&i.Jan,
			&i.Mpn,
			&i.Nsn,
			&i.Upc,
			&i.Qr,
			&i.Sku,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemIdentifier = `-- name: UpdateItemIdentifier :one

UPDATE item_identifiers
SET
    updated_at = $1::timestamp,
    ean = COALESCE($2, ean),
    gtin = COALESCE($3, gtin),
    isbn = COALESCE($4, isbn),
    jan = COALESCE($5, jan),
    mpn = COALESCE($6, mpn),
    nsn = COALESCE($7, nsn),
    upc = COALESCE($8, upc),
    qr = COALESCE($9, qr),
    sku = COALESCE($10, sku)
WHERE id = $11 AND account_id = $12
RETURNING
    id,
    created_at,
    updated_at,
    ean,
    gtin,
    isbn,
    jan,
    mpn,
    nsn,
    upc,
    qr,
    sku,
    item_id
`

type UpdateItemIdentifierParams struct {
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdateItemIdentifierRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	ItemID    uuid.UUID
}

func (q *Queries) UpdateItemIdentifier(ctx context.Context, arg UpdateItemIdentifierParams) (UpdateItemIdentifierRow, error) {
	row := q.db.QueryRow(ctx, updateItemIdentifier,
		arg.UpdatedAt,
		arg.Ean,
		arg.Gtin,
		arg.Isbn,
		arg.Jan,
		arg.Mpn,
		arg.Nsn,
		arg.Upc,
		arg.Qr,
		arg.Sku,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateItemIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Ean,
		&i.Gtin,
		&i.Isbn,
		&i.Jan,
		&i.Mpn,
		&i.Nsn,
		&i.Upc,
		&i.Qr,
		&i.Sku,
		&i.ItemID,
	)
	return i, err
}
