// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item_variant_attributes.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CreateItemVariantAttributeParams struct {
	Name      string
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

const deleteItemVariantAttribute = `-- name: DeleteItemVariantAttribute :exec

DELETE FROM item_variant_attributes
WHERE id = $1 AND account_id = $2
`

type DeleteItemVariantAttributeParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteItemVariantAttribute(ctx context.Context, arg DeleteItemVariantAttributeParams) error {
	_, err := q.db.Exec(ctx, deleteItemVariantAttribute, arg.ID, arg.AccountID)
	return err
}

const getItemVariantAttribute = `-- name: GetItemVariantAttribute :one

SELECT
    id,
    created_at,
    updated_at,
    name,
    item_id
FROM item_variant_attributes
WHERE id = $1 AND account_id = $2
`

type GetItemVariantAttributeParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetItemVariantAttributeRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ItemID    uuid.UUID
}

func (q *Queries) GetItemVariantAttribute(ctx context.Context, arg GetItemVariantAttributeParams) (GetItemVariantAttributeRow, error) {
	row := q.db.QueryRow(ctx, getItemVariantAttribute, arg.ID, arg.AccountID)
	var i GetItemVariantAttributeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ItemID,
	)
	return i, err
}

const listItemVariantAttributes = `-- name: ListItemVariantAttributes :many

SELECT id, created_at, updated_at, name, item_id
FROM
(
    SELECT
        item_variant_attributes.id,
        item_variant_attributes.created_at,
        item_variant_attributes.updated_at,
        item_variant_attributes.name,
        item_variant_attributes.item_id
    FROM item_variant_attributes
    WHERE item_variant_attributes.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR item_variant_attributes.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR item_variant_attributes.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR item_variant_attributes.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR item_variant_attributes.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR item_variant_attributes.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR item_variant_attributes.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR item_variant_attributes.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR item_variant_attributes.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR 
            (
                (
                    $11::timestamp,
                    $10::uuid
                ) > (item_variant_attributes.created_at, item_variant_attributes.id)
            )
        )
    AND 
        (
            $12::uuid IS NULL
            OR 
            (
                (
                    $13::timestamp,
                    $12::uuid
                ) < (item_variant_attributes.created_at, item_variant_attributes.id)
            )
        )
    AND 
        (
            $14::text IS NULL 
            OR item_variant_attributes.name ~~* CONCAT('%', $14::text, '%')
        )
    ORDER BY 
    (
        CASE 
            WHEN $12::uuid IS NOT NULL 
            THEN (item_variant_attributes.created_at, item_variant_attributes.id)
        END
    ) ASC,
    (item_variant_attributes.created_at, item_variant_attributes.id) DESC
    LIMIT COALESCE($15::integer, 10) + 1
)
ORDER BY created_at DESC, id DESC
`

type ListItemVariantAttributesParams struct {
	AccountID         uuid.UUID
	CreatedAtGt       sql.NullTime
	CreatedAtLt       sql.NullTime
	CreatedAtGte      sql.NullTime
	CreatedAtLte      sql.NullTime
	UpdatedAtGt       sql.NullTime
	UpdatedAtLt       sql.NullTime
	UpdatedAtGte      sql.NullTime
	UpdatedAtLte      sql.NullTime
	StartingAfter     uuid.NullUUID
	StartingAfterDate sql.NullTime
	EndingBefore      uuid.NullUUID
	EndingBeforeDate  sql.NullTime
	Name              sql.NullString
	Limit             sql.NullInt32
}

type ListItemVariantAttributesRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ItemID    uuid.UUID
}

func (q *Queries) ListItemVariantAttributes(ctx context.Context, arg ListItemVariantAttributesParams) ([]ListItemVariantAttributesRow, error) {
	rows, err := q.db.Query(ctx, listItemVariantAttributes,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.StartingAfterDate,
		arg.EndingBefore,
		arg.EndingBeforeDate,
		arg.Name,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemVariantAttributesRow
	for rows.Next() {
		var i ListItemVariantAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.ItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemVariantAttribute = `-- name: UpdateItemVariantAttribute :one

UPDATE item_variant_attributes
SET
    updated_at = $1::timestamp,
    name = COALESCE($2, name)
WHERE id = $3 AND account_id = $4
RETURNING
    id,
    created_at,
    updated_at,
    name,
    item_id
`

type UpdateItemVariantAttributeParams struct {
	UpdatedAt time.Time
	Name      sql.NullString
	ID        uuid.UUID
	AccountID uuid.UUID
}

type UpdateItemVariantAttributeRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	ItemID    uuid.UUID
}

func (q *Queries) UpdateItemVariantAttribute(ctx context.Context, arg UpdateItemVariantAttributeParams) (UpdateItemVariantAttributeRow, error) {
	row := q.db.QueryRow(ctx, updateItemVariantAttribute,
		arg.UpdatedAt,
		arg.Name,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateItemVariantAttributeRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.ItemID,
	)
	return i, err
}
