// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createItem = `-- name: CreateItem :one
INSERT INTO items 
(
    active,
    description,
    name,
    has_variants,
    price_amount,
    price_currency,
    type,
    account_id,
    group_id,
    inventory_id
)
VALUES 
(
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING
    id,
    created_at,
    updated_at,
    active,
    description,
    group_id,
    has_variants,
    inventory_id,
    name,
    price_amount,
    price_currency,
    type,
    variant
`

type CreateItemParams struct {
	Active        bool
	Description   sql.NullString
	Name          string
	HasVariants   bool
	PriceAmount   sql.NullInt32
	PriceCurrency NullCurrency
	Type          ItemType
	AccountID     uuid.UUID
	GroupID       uuid.NullUUID
	InventoryID   uuid.NullUUID
}

type CreateItemRow struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Active        bool
	Description   sql.NullString
	GroupID       uuid.NullUUID
	HasVariants   bool
	InventoryID   uuid.NullUUID
	Name          string
	PriceAmount   sql.NullInt32
	PriceCurrency NullCurrency
	Type          ItemType
	Variant       bool
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (CreateItemRow, error) {
	row := q.db.QueryRow(ctx, createItem,
		arg.Active,
		arg.Description,
		arg.Name,
		arg.HasVariants,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Type,
		arg.AccountID,
		arg.GroupID,
		arg.InventoryID,
	)
	var i CreateItemRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.Description,
		&i.GroupID,
		&i.HasVariants,
		&i.InventoryID,
		&i.Name,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.Type,
		&i.Variant,
	)
	return i, err
}

type CreateItemVariantsParams struct {
	Active        bool
	Description   sql.NullString
	Name          string
	PriceAmount   sql.NullInt32
	PriceCurrency NullCurrency
	Type          ItemType
	Variant       bool
	AccountID     uuid.UUID
	GroupID       uuid.NullUUID
	InventoryID   uuid.NullUUID
	ParentItemID  uuid.NullUUID
}

const deleteItem = `-- name: DeleteItem :exec

DELETE FROM items
WHERE id = $1 AND account_id = $2
`

type DeleteItemParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

func (q *Queries) DeleteItem(ctx context.Context, arg DeleteItemParams) error {
	_, err := q.db.Exec(ctx, deleteItem, arg.ID, arg.AccountID)
	return err
}

const getItem = `-- name: GetItem :one

SELECT
    items.id,
    items.created_at,
    items.updated_at,
    items.active,
    items.description,
    items.group_id,
    items.has_variants,
    item_identifiers.id AS item_identifiers_id,
    items.inventory_id,
    items.name,
    items.parent_item_id,
    items.price_amount,
    items.price_currency,
    items.type,
    items.variant
FROM items
LEFT JOIN item_identifiers ON items.id = item_identifiers.item_id
WHERE items.id = $1 AND items.account_id = $2
`

type GetItemParams struct {
	ID        uuid.UUID
	AccountID uuid.UUID
}

type GetItemRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Active            bool
	Description       sql.NullString
	GroupID           uuid.NullUUID
	HasVariants       bool
	ItemIdentifiersID uuid.NullUUID
	InventoryID       uuid.NullUUID
	Name              string
	ParentItemID      uuid.NullUUID
	PriceAmount       sql.NullInt32
	PriceCurrency     NullCurrency
	Type              ItemType
	Variant           bool
}

func (q *Queries) GetItem(ctx context.Context, arg GetItemParams) (GetItemRow, error) {
	row := q.db.QueryRow(ctx, getItem, arg.ID, arg.AccountID)
	var i GetItemRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.Description,
		&i.GroupID,
		&i.HasVariants,
		&i.ItemIdentifiersID,
		&i.InventoryID,
		&i.Name,
		&i.ParentItemID,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.Type,
		&i.Variant,
	)
	return i, err
}

const listItemIdsByInventory = `-- name: ListItemIdsByInventory :many

SELECT id
FROM
(
    SELECT
        items.id,
        items.created_at
    FROM items
    WHERE items.account_id = $1 AND items.inventory_id = $2::uuid
    AND
        (
            $3::uuid IS NULL
            OR 
            (
                (
                    $4::timestamp,
                    $3::uuid
                ) > (items.created_at, items.id)
            )
        )
    AND 
        (
            $5::uuid IS NULL
            OR 
            (
                (
                    $6::timestamp,
                    $5::uuid
                ) < (items.created_at, items.id)
            )
        )
    ORDER BY 
    (
        CASE 
            WHEN $5::uuid IS NOT NULL 
            THEN (items.created_at, items.id)
        END
    ) ASC,
    (items.created_at, items.id) DESC
    LIMIT COALESCE($7::integer, 10) + 1
)
ORDER BY created_at DESC, id DESC
`

type ListItemIdsByInventoryParams struct {
	AccountID         uuid.UUID
	InventoryID       uuid.UUID
	StartingAfter     uuid.NullUUID
	StartingAfterDate sql.NullTime
	EndingBefore      uuid.NullUUID
	EndingBeforeDate  sql.NullTime
	Limit             sql.NullInt32
}

func (q *Queries) ListItemIdsByInventory(ctx context.Context, arg ListItemIdsByInventoryParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listItemIdsByInventory,
		arg.AccountID,
		arg.InventoryID,
		arg.StartingAfter,
		arg.StartingAfterDate,
		arg.EndingBefore,
		arg.EndingBeforeDate,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many

SELECT id, created_at, updated_at, active, description, group_id, has_variants, item_identifiers_id, inventory_id, name, parent_item_id, price_amount, price_currency, type, variant
FROM
(
    SELECT
        items.id,
        items.created_at,
        items.updated_at,
        items.active,
        items.description,
        items.group_id,
        items.has_variants,
        item_identifiers.id AS item_identifiers_id,
        items.inventory_id,
        items.name,
        items.parent_item_id,
        items.price_amount,
        items.price_currency,
        items.type,
        items.variant
    FROM items
    LEFT JOIN item_identifiers ON items.id = item_identifiers.item_id
    WHERE items.account_id = $1
    AND
        (
            $2::timestamp IS NULL 
            OR items.created_at > $2::timestamp
        )
    AND 
        (
            $3::timestamp IS NULL 
            OR items.created_at < $3::timestamp
        )
    AND 
        (
            $4::timestamp IS NULL 
            OR items.created_at >= $4::timestamp
        )
    AND 
        (
            $5::timestamp IS NULL 
            OR items.created_at <= $5::timestamp
        )
    AND 
        (
            $6::timestamp IS NULL 
            OR items.updated_at > $6::timestamp
        )
    AND 
        (
            $7::timestamp IS NULL 
            OR items.updated_at < $7::timestamp
        )
    AND 
        (
            $8::timestamp IS NULL 
            OR items.updated_at >= $8::timestamp
        )
    AND 
        (
            $9::timestamp IS NULL 
            OR items.updated_at <= $9::timestamp
        )
    AND 
        (
            $10::uuid IS NULL
            OR 
            (
                (
                    $11::timestamp,
                    $10::uuid
                ) > (items.created_at, items.id)
            )
        )
    AND 
        (
            $12::uuid IS NULL
            OR 
            (
                (
                    $13::timestamp,
                    $12::uuid
                ) < (items.created_at, items.id)
            )
        )
    AND
        (
            $14::boolean IS NULL
            OR items.active = $14::boolean
        )
    AND 
        (
            $15::text IS NULL 
            OR items.description ~~* CONCAT('%', $15::text, '%')
        )
    AND 
        (
            $16::uuid IS NULL 
            OR items.group_id = $16::uuid
        )
    AND
        (
            $17::boolean IS NULL 
            OR items.has_variants = $17::boolean
        )
    AND 
        (
            $18::uuid IS NULL 
            OR items.inventory_id = $18::uuid
        )
    AND 
        (
            $19::text IS NULL 
            OR items.name ~~* CONCAT('%', $19::text, '%')
        )
    AND 
        (
            $20::uuid IS NULL 
            OR items.parent_item_id = $20::uuid
        )
    AND 
        (
            $21::integer IS NULL 
            OR items.price_amount = $21::integer
        )
    AND 
        (
            $22::currency IS NULL 
            OR items.price_currency = $22::currency
        )
    AND
        (
            $23::item_type IS NULL 
            OR items.type = $23::item_type
        )
    AND
        (
            $24::boolean IS NULL 
            OR items.variant = $24::boolean
        )
    ORDER BY 
    (
        CASE 
            WHEN $12::uuid IS NOT NULL 
            THEN (items.created_at, items.id)
        END
    ) ASC,
    (items.created_at, items.id) DESC
    LIMIT COALESCE($25::integer, 10) + 1
)
ORDER BY created_at DESC, id DESC
`

type ListItemsParams struct {
	AccountID         uuid.UUID
	CreatedAtGt       sql.NullTime
	CreatedAtLt       sql.NullTime
	CreatedAtGte      sql.NullTime
	CreatedAtLte      sql.NullTime
	UpdatedAtGt       sql.NullTime
	UpdatedAtLt       sql.NullTime
	UpdatedAtGte      sql.NullTime
	UpdatedAtLte      sql.NullTime
	StartingAfter     uuid.NullUUID
	StartingAfterDate sql.NullTime
	EndingBefore      uuid.NullUUID
	EndingBeforeDate  sql.NullTime
	Active            sql.NullBool
	Description       sql.NullString
	GroupID           uuid.NullUUID
	HasVariants       sql.NullBool
	InventoryID       uuid.NullUUID
	Name              sql.NullString
	ParentItemID      uuid.NullUUID
	PriceAmount       sql.NullInt32
	PriceCurrency     NullCurrency
	Type              NullItemType
	Variant           sql.NullBool
	Limit             sql.NullInt32
}

type ListItemsRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Active            bool
	Description       sql.NullString
	GroupID           uuid.NullUUID
	HasVariants       bool
	ItemIdentifiersID uuid.NullUUID
	InventoryID       uuid.NullUUID
	Name              string
	ParentItemID      uuid.NullUUID
	PriceAmount       sql.NullInt32
	PriceCurrency     NullCurrency
	Type              ItemType
	Variant           bool
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems,
		arg.AccountID,
		arg.CreatedAtGt,
		arg.CreatedAtLt,
		arg.CreatedAtGte,
		arg.CreatedAtLte,
		arg.UpdatedAtGt,
		arg.UpdatedAtLt,
		arg.UpdatedAtGte,
		arg.UpdatedAtLte,
		arg.StartingAfter,
		arg.StartingAfterDate,
		arg.EndingBefore,
		arg.EndingBeforeDate,
		arg.Active,
		arg.Description,
		arg.GroupID,
		arg.HasVariants,
		arg.InventoryID,
		arg.Name,
		arg.ParentItemID,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.Type,
		arg.Variant,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.Description,
			&i.GroupID,
			&i.HasVariants,
			&i.ItemIdentifiersID,
			&i.InventoryID,
			&i.Name,
			&i.ParentItemID,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.Type,
			&i.Variant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsByIds = `-- name: ListItemsByIds :many

SELECT
    items.id,
    items.created_at,
    items.updated_at,
    items.active,
    items.description,
    items.group_id,
    items.has_variants,
    item_identifiers.id AS item_identifiers_id,
    items.inventory_id,
    items.name,
    items.parent_item_id,
    items.price_amount,
    items.price_currency,
    items.type,
    items.variant
FROM items
LEFT JOIN item_identifiers ON items.id = item_identifiers.item_id
WHERE items.account_id = $1
    AND items.id = ANY($2::uuid[])
ORDER BY items.created_at DESC, items.id DESC
`

type ListItemsByIdsParams struct {
	AccountID uuid.UUID
	Ids       []uuid.UUID
}

type ListItemsByIdsRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Active            bool
	Description       sql.NullString
	GroupID           uuid.NullUUID
	HasVariants       bool
	ItemIdentifiersID uuid.NullUUID
	InventoryID       uuid.NullUUID
	Name              string
	ParentItemID      uuid.NullUUID
	PriceAmount       sql.NullInt32
	PriceCurrency     NullCurrency
	Type              ItemType
	Variant           bool
}

func (q *Queries) ListItemsByIds(ctx context.Context, arg ListItemsByIdsParams) ([]ListItemsByIdsRow, error) {
	rows, err := q.db.Query(ctx, listItemsByIds, arg.AccountID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsByIdsRow
	for rows.Next() {
		var i ListItemsByIdsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Active,
			&i.Description,
			&i.GroupID,
			&i.HasVariants,
			&i.ItemIdentifiersID,
			&i.InventoryID,
			&i.Name,
			&i.ParentItemID,
			&i.PriceAmount,
			&i.PriceCurrency,
			&i.Type,
			&i.Variant,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItem = `-- name: UpdateItem :one

UPDATE items
SET
    updated_at = $1::timestamp,
    active = COALESCE($2::boolean, active),
    description = COALESCE($3, description),
    group_id = COALESCE($4, group_id),
    has_variants = COALESCE($5, has_variants),
    inventory_id = COALESCE($6, inventory_id),
    name = COALESCE($7, name),
    price_amount = COALESCE($8, price_amount),
    price_currency = COALESCE($9, price_currency)
FROM
    items AS i
    LEFT JOIN item_identifiers ON i.id = item_identifiers.item_id
WHERE
    i.id = $10
    AND i.account_id = $11
    AND i.id = items.id
RETURNING
    items.id,
    items.created_at,
    items.updated_at,
    items.active,
    items.description,
    items.group_id,
    items.has_variants,
    item_identifiers.id AS item_identifiers_id,
    items.inventory_id,
    items.name,
    items.parent_item_id,
    items.price_amount,
    items.price_currency,
    items.type,
    items.variant
`

type UpdateItemParams struct {
	UpdatedAt     time.Time
	Active        sql.NullBool
	Description   sql.NullString
	GroupID       uuid.NullUUID
	HasVariants   sql.NullBool
	InventoryID   uuid.NullUUID
	Name          sql.NullString
	PriceAmount   sql.NullInt32
	PriceCurrency NullCurrency
	ID            uuid.UUID
	AccountID     uuid.UUID
}

type UpdateItemRow struct {
	ID                uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	Active            bool
	Description       sql.NullString
	GroupID           uuid.NullUUID
	HasVariants       bool
	ItemIdentifiersID uuid.UUID
	InventoryID       uuid.NullUUID
	Name              string
	ParentItemID      uuid.NullUUID
	PriceAmount       sql.NullInt32
	PriceCurrency     NullCurrency
	Type              ItemType
	Variant           bool
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (UpdateItemRow, error) {
	row := q.db.QueryRow(ctx, updateItem,
		arg.UpdatedAt,
		arg.Active,
		arg.Description,
		arg.GroupID,
		arg.HasVariants,
		arg.InventoryID,
		arg.Name,
		arg.PriceAmount,
		arg.PriceCurrency,
		arg.ID,
		arg.AccountID,
	)
	var i UpdateItemRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Active,
		&i.Description,
		&i.GroupID,
		&i.HasVariants,
		&i.ItemIdentifiersID,
		&i.InventoryID,
		&i.Name,
		&i.ParentItemID,
		&i.PriceAmount,
		&i.PriceCurrency,
		&i.Type,
		&i.Variant,
	)
	return i, err
}
