// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Country string

const (
	CountryAF Country = "AF"
	CountryAX Country = "AX"
	CountryAL Country = "AL"
	CountryDZ Country = "DZ"
	CountryAS Country = "AS"
	CountryAD Country = "AD"
	CountryAO Country = "AO"
	CountryAI Country = "AI"
	CountryAQ Country = "AQ"
	CountryAG Country = "AG"
	CountryAR Country = "AR"
	CountryAM Country = "AM"
	CountryAW Country = "AW"
	CountryAU Country = "AU"
	CountryAT Country = "AT"
	CountryAZ Country = "AZ"
	CountryBS Country = "BS"
	CountryBH Country = "BH"
	CountryBD Country = "BD"
	CountryBB Country = "BB"
	CountryBY Country = "BY"
	CountryBE Country = "BE"
	CountryBZ Country = "BZ"
	CountryBJ Country = "BJ"
	CountryBM Country = "BM"
	CountryBT Country = "BT"
	CountryBO Country = "BO"
	CountryBQ Country = "BQ"
	CountryBA Country = "BA"
	CountryBW Country = "BW"
	CountryBV Country = "BV"
	CountryBR Country = "BR"
	CountryIO Country = "IO"
	CountryBN Country = "BN"
	CountryBG Country = "BG"
	CountryBF Country = "BF"
	CountryBI Country = "BI"
	CountryCV Country = "CV"
	CountryKH Country = "KH"
	CountryCM Country = "CM"
	CountryCA Country = "CA"
	CountryKY Country = "KY"
	CountryCF Country = "CF"
	CountryTD Country = "TD"
	CountryCL Country = "CL"
	CountryCN Country = "CN"
	CountryCX Country = "CX"
	CountryCC Country = "CC"
	CountryCO Country = "CO"
	CountryKM Country = "KM"
	CountryCD Country = "CD"
	CountryCG Country = "CG"
	CountryCK Country = "CK"
	CountryCR Country = "CR"
	CountryCI Country = "CI"
	CountryHR Country = "HR"
	CountryCU Country = "CU"
	CountryCW Country = "CW"
	CountryCY Country = "CY"
	CountryCZ Country = "CZ"
	CountryDK Country = "DK"
	CountryDJ Country = "DJ"
	CountryDM Country = "DM"
	CountryDO Country = "DO"
	CountryEC Country = "EC"
	CountryEG Country = "EG"
	CountrySV Country = "SV"
	CountryGQ Country = "GQ"
	CountryER Country = "ER"
	CountryEE Country = "EE"
	CountrySZ Country = "SZ"
	CountryET Country = "ET"
	CountryFK Country = "FK"
	CountryFO Country = "FO"
	CountryFJ Country = "FJ"
	CountryFI Country = "FI"
	CountryFR Country = "FR"
	CountryGF Country = "GF"
	CountryPF Country = "PF"
	CountryTF Country = "TF"
	CountryGA Country = "GA"
	CountryGM Country = "GM"
	CountryGE Country = "GE"
	CountryDE Country = "DE"
	CountryGH Country = "GH"
	CountryGI Country = "GI"
	CountryGR Country = "GR"
	CountryGL Country = "GL"
	CountryGD Country = "GD"
	CountryGP Country = "GP"
	CountryGU Country = "GU"
	CountryGT Country = "GT"
	CountryGG Country = "GG"
	CountryGN Country = "GN"
	CountryGW Country = "GW"
	CountryGY Country = "GY"
	CountryHT Country = "HT"
	CountryHM Country = "HM"
	CountryVA Country = "VA"
	CountryHN Country = "HN"
	CountryHK Country = "HK"
	CountryHU Country = "HU"
	CountryIS Country = "IS"
	CountryIN Country = "IN"
	CountryID Country = "ID"
	CountryIR Country = "IR"
	CountryIQ Country = "IQ"
	CountryIE Country = "IE"
	CountryIM Country = "IM"
	CountryIL Country = "IL"
	CountryIT Country = "IT"
	CountryJM Country = "JM"
	CountryJP Country = "JP"
	CountryJE Country = "JE"
	CountryJO Country = "JO"
	CountryKZ Country = "KZ"
	CountryKE Country = "KE"
	CountryKI Country = "KI"
	CountryKP Country = "KP"
	CountryKR Country = "KR"
	CountryKW Country = "KW"
	CountryKG Country = "KG"
	CountryLA Country = "LA"
	CountryLV Country = "LV"
	CountryLB Country = "LB"
	CountryLS Country = "LS"
	CountryLR Country = "LR"
	CountryLY Country = "LY"
	CountryLI Country = "LI"
	CountryLT Country = "LT"
	CountryLU Country = "LU"
	CountryMO Country = "MO"
	CountryMK Country = "MK"
	CountryMG Country = "MG"
	CountryMW Country = "MW"
	CountryMY Country = "MY"
	CountryMV Country = "MV"
	CountryML Country = "ML"
	CountryMT Country = "MT"
	CountryMH Country = "MH"
	CountryMQ Country = "MQ"
	CountryMR Country = "MR"
	CountryMU Country = "MU"
	CountryYT Country = "YT"
	CountryMX Country = "MX"
	CountryFM Country = "FM"
	CountryMD Country = "MD"
	CountryMC Country = "MC"
	CountryMN Country = "MN"
	CountryME Country = "ME"
	CountryMS Country = "MS"
	CountryMA Country = "MA"
	CountryMZ Country = "MZ"
	CountryMM Country = "MM"
	CountryNA Country = "NA"
	CountryNR Country = "NR"
	CountryNP Country = "NP"
	CountryNL Country = "NL"
	CountryNC Country = "NC"
	CountryNZ Country = "NZ"
	CountryNI Country = "NI"
	CountryNE Country = "NE"
	CountryNG Country = "NG"
	CountryNU Country = "NU"
	CountryNF Country = "NF"
	CountryMP Country = "MP"
	CountryNO Country = "NO"
	CountryOM Country = "OM"
	CountryPK Country = "PK"
	CountryPW Country = "PW"
	CountryPS Country = "PS"
	CountryPA Country = "PA"
	CountryPG Country = "PG"
	CountryPY Country = "PY"
	CountryPE Country = "PE"
	CountryPH Country = "PH"
	CountryPN Country = "PN"
	CountryPL Country = "PL"
	CountryPT Country = "PT"
	CountryPR Country = "PR"
	CountryQA Country = "QA"
	CountryRE Country = "RE"
	CountryRO Country = "RO"
	CountryRU Country = "RU"
	CountryRW Country = "RW"
	CountryBL Country = "BL"
	CountrySH Country = "SH"
	CountryKN Country = "KN"
	CountryLC Country = "LC"
	CountryMF Country = "MF"
	CountryPM Country = "PM"
	CountryVC Country = "VC"
	CountryWS Country = "WS"
	CountrySM Country = "SM"
	CountryST Country = "ST"
	CountrySA Country = "SA"
	CountrySN Country = "SN"
	CountryRS Country = "RS"
	CountrySC Country = "SC"
	CountrySL Country = "SL"
	CountrySG Country = "SG"
	CountrySX Country = "SX"
	CountrySK Country = "SK"
	CountrySI Country = "SI"
	CountrySB Country = "SB"
	CountrySO Country = "SO"
	CountryZA Country = "ZA"
	CountryGS Country = "GS"
	CountrySS Country = "SS"
	CountryES Country = "ES"
	CountryLK Country = "LK"
	CountrySD Country = "SD"
	CountrySR Country = "SR"
	CountrySJ Country = "SJ"
	CountrySE Country = "SE"
	CountryCH Country = "CH"
	CountrySY Country = "SY"
	CountryTW Country = "TW"
	CountryTJ Country = "TJ"
	CountryTZ Country = "TZ"
	CountryTH Country = "TH"
	CountryTL Country = "TL"
	CountryTG Country = "TG"
	CountryTK Country = "TK"
	CountryTO Country = "TO"
	CountryTT Country = "TT"
	CountryTN Country = "TN"
	CountryTR Country = "TR"
	CountryTM Country = "TM"
	CountryTC Country = "TC"
	CountryTV Country = "TV"
	CountryUG Country = "UG"
	CountryUA Country = "UA"
	CountryAE Country = "AE"
	CountryGB Country = "GB"
	CountryUM Country = "UM"
	CountryUS Country = "US"
	CountryUY Country = "UY"
	CountryUZ Country = "UZ"
	CountryVU Country = "VU"
	CountryVE Country = "VE"
	CountryVN Country = "VN"
	CountryVG Country = "VG"
	CountryVI Country = "VI"
	CountryWF Country = "WF"
	CountryEH Country = "EH"
	CountryYE Country = "YE"
	CountryZM Country = "ZM"
	CountryZW Country = "ZW"
)

func (e *Country) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Country(s)
	case string:
		*e = Country(s)
	default:
		return fmt.Errorf("unsupported scan type for Country: %T", src)
	}
	return nil
}

type NullCountry struct {
	Country Country
	Valid   bool // Valid is true if Country is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCountry) Scan(value interface{}) error {
	if value == nil {
		ns.Country, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Country.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCountry) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Country), nil
}

type Currency string

const (
	CurrencyAED Currency = "AED"
	CurrencyAFN Currency = "AFN"
	CurrencyALL Currency = "ALL"
	CurrencyAMD Currency = "AMD"
	CurrencyAOA Currency = "AOA"
	CurrencyARS Currency = "ARS"
	CurrencyAUD Currency = "AUD"
	CurrencyAWG Currency = "AWG"
	CurrencyAZN Currency = "AZN"
	CurrencyBAM Currency = "BAM"
	CurrencyBBD Currency = "BBD"
	CurrencyBDT Currency = "BDT"
	CurrencyBGN Currency = "BGN"
	CurrencyBHD Currency = "BHD"
	CurrencyBIF Currency = "BIF"
	CurrencyBMD Currency = "BMD"
	CurrencyBND Currency = "BND"
	CurrencyBOB Currency = "BOB"
	CurrencyBOV Currency = "BOV"
	CurrencyBRL Currency = "BRL"
	CurrencyBSD Currency = "BSD"
	CurrencyBTN Currency = "BTN"
	CurrencyBWP Currency = "BWP"
	CurrencyBYN Currency = "BYN"
	CurrencyBZD Currency = "BZD"
	CurrencyCAD Currency = "CAD"
	CurrencyCDF Currency = "CDF"
	CurrencyCHE Currency = "CHE"
	CurrencyCHF Currency = "CHF"
	CurrencyCHW Currency = "CHW"
	CurrencyCLF Currency = "CLF"
	CurrencyCLP Currency = "CLP"
	CurrencyCNY Currency = "CNY"
	CurrencyCOP Currency = "COP"
	CurrencyCOU Currency = "COU"
	CurrencyCRC Currency = "CRC"
	CurrencyCUP Currency = "CUP"
	CurrencyCVE Currency = "CVE"
	CurrencyCZK Currency = "CZK"
	CurrencyDJF Currency = "DJF"
	CurrencyDKK Currency = "DKK"
	CurrencyDOP Currency = "DOP"
	CurrencyDZD Currency = "DZD"
	CurrencyEGP Currency = "EGP"
	CurrencyERN Currency = "ERN"
	CurrencyETB Currency = "ETB"
	CurrencyEUR Currency = "EUR"
	CurrencyFJD Currency = "FJD"
	CurrencyFKP Currency = "FKP"
	CurrencyGBP Currency = "GBP"
	CurrencyGEL Currency = "GEL"
	CurrencyGHS Currency = "GHS"
	CurrencyGIP Currency = "GIP"
	CurrencyGMD Currency = "GMD"
	CurrencyGNF Currency = "GNF"
	CurrencyGTQ Currency = "GTQ"
	CurrencyGYD Currency = "GYD"
	CurrencyHKD Currency = "HKD"
	CurrencyHNL Currency = "HNL"
	CurrencyHTG Currency = "HTG"
	CurrencyHUF Currency = "HUF"
	CurrencyIDR Currency = "IDR"
	CurrencyILS Currency = "ILS"
	CurrencyINR Currency = "INR"
	CurrencyIQD Currency = "IQD"
	CurrencyIRR Currency = "IRR"
	CurrencyISK Currency = "ISK"
	CurrencyJMD Currency = "JMD"
	CurrencyJOD Currency = "JOD"
	CurrencyJPY Currency = "JPY"
	CurrencyKES Currency = "KES"
	CurrencyKGS Currency = "KGS"
	CurrencyKHR Currency = "KHR"
	CurrencyKMF Currency = "KMF"
	CurrencyKPW Currency = "KPW"
	CurrencyKRW Currency = "KRW"
	CurrencyKWD Currency = "KWD"
	CurrencyKYD Currency = "KYD"
	CurrencyKZT Currency = "KZT"
	CurrencyLAK Currency = "LAK"
	CurrencyLBP Currency = "LBP"
	CurrencyLKR Currency = "LKR"
	CurrencyLRD Currency = "LRD"
	CurrencyLSL Currency = "LSL"
	CurrencyLYD Currency = "LYD"
	CurrencyMAD Currency = "MAD"
	CurrencyMDL Currency = "MDL"
	CurrencyMGA Currency = "MGA"
	CurrencyMKD Currency = "MKD"
	CurrencyMMK Currency = "MMK"
	CurrencyMNT Currency = "MNT"
	CurrencyMOP Currency = "MOP"
	CurrencyMRU Currency = "MRU"
	CurrencyMUR Currency = "MUR"
	CurrencyMVR Currency = "MVR"
	CurrencyMWK Currency = "MWK"
	CurrencyMXN Currency = "MXN"
	CurrencyMXV Currency = "MXV"
	CurrencyMYR Currency = "MYR"
	CurrencyMZN Currency = "MZN"
	CurrencyNAD Currency = "NAD"
	CurrencyNGN Currency = "NGN"
	CurrencyNIO Currency = "NIO"
	CurrencyNOK Currency = "NOK"
	CurrencyNPR Currency = "NPR"
	CurrencyNZD Currency = "NZD"
	CurrencyOMR Currency = "OMR"
	CurrencyPAB Currency = "PAB"
	CurrencyPEN Currency = "PEN"
	CurrencyPGK Currency = "PGK"
	CurrencyPHP Currency = "PHP"
	CurrencyPKR Currency = "PKR"
	CurrencyPLN Currency = "PLN"
	CurrencyPYG Currency = "PYG"
	CurrencyQAR Currency = "QAR"
	CurrencyRON Currency = "RON"
	CurrencyRSD Currency = "RSD"
	CurrencyRUB Currency = "RUB"
	CurrencyRWF Currency = "RWF"
	CurrencySAR Currency = "SAR"
	CurrencySBD Currency = "SBD"
	CurrencySCR Currency = "SCR"
	CurrencySDG Currency = "SDG"
	CurrencySEK Currency = "SEK"
	CurrencySGD Currency = "SGD"
	CurrencySHP Currency = "SHP"
	CurrencySLE Currency = "SLE"
	CurrencySOS Currency = "SOS"
	CurrencySRD Currency = "SRD"
	CurrencySSP Currency = "SSP"
	CurrencySTN Currency = "STN"
	CurrencySVC Currency = "SVC"
	CurrencySYP Currency = "SYP"
	CurrencySZL Currency = "SZL"
	CurrencyTHB Currency = "THB"
	CurrencyTJS Currency = "TJS"
	CurrencyTMT Currency = "TMT"
	CurrencyTND Currency = "TND"
	CurrencyTOP Currency = "TOP"
	CurrencyTRY Currency = "TRY"
	CurrencyTTD Currency = "TTD"
	CurrencyTWD Currency = "TWD"
	CurrencyTZS Currency = "TZS"
	CurrencyUAH Currency = "UAH"
	CurrencyUGX Currency = "UGX"
	CurrencyUSD Currency = "USD"
	CurrencyUSN Currency = "USN"
	CurrencyUYI Currency = "UYI"
	CurrencyUYU Currency = "UYU"
	CurrencyUYW Currency = "UYW"
	CurrencyUZS Currency = "UZS"
	CurrencyVED Currency = "VED"
	CurrencyVES Currency = "VES"
	CurrencyVND Currency = "VND"
	CurrencyVUV Currency = "VUV"
	CurrencyWST Currency = "WST"
	CurrencyXAD Currency = "XAD"
	CurrencyXAF Currency = "XAF"
	CurrencyXAG Currency = "XAG"
	CurrencyXAU Currency = "XAU"
	CurrencyXBA Currency = "XBA"
	CurrencyXBB Currency = "XBB"
	CurrencyXBC Currency = "XBC"
	CurrencyXBD Currency = "XBD"
	CurrencyXCD Currency = "XCD"
	CurrencyXCG Currency = "XCG"
	CurrencyXDR Currency = "XDR"
	CurrencyXOF Currency = "XOF"
	CurrencyXPD Currency = "XPD"
	CurrencyXPF Currency = "XPF"
	CurrencyXPT Currency = "XPT"
	CurrencyXSU Currency = "XSU"
	CurrencyXTS Currency = "XTS"
	CurrencyXUA Currency = "XUA"
	CurrencyXXX Currency = "XXX"
	CurrencyYER Currency = "YER"
	CurrencyZAR Currency = "ZAR"
	CurrencyZMW Currency = "ZMW"
	CurrencyZWG Currency = "ZWG"
)

func (e *Currency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Currency(s)
	case string:
		*e = Currency(s)
	default:
		return fmt.Errorf("unsupported scan type for Currency: %T", src)
	}
	return nil
}

type NullCurrency struct {
	Currency Currency
	Valid    bool // Valid is true if Currency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrency) Scan(value interface{}) error {
	if value == nil {
		ns.Currency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Currency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Currency), nil
}

type InventoryMovementReferenceType string

const (
	InventoryMovementReferenceTypeMANUAL             InventoryMovementReferenceType = "MANUAL"
	InventoryMovementReferenceTypeORDER              InventoryMovementReferenceType = "ORDER"
	InventoryMovementReferenceTypeRETURN             InventoryMovementReferenceType = "RETURN"
	InventoryMovementReferenceTypeRESERVATIONRELEASE InventoryMovementReferenceType = "RESERVATION_RELEASE"
	InventoryMovementReferenceTypeSALE               InventoryMovementReferenceType = "SALE"
)

func (e *InventoryMovementReferenceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryMovementReferenceType(s)
	case string:
		*e = InventoryMovementReferenceType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryMovementReferenceType: %T", src)
	}
	return nil
}

type NullInventoryMovementReferenceType struct {
	InventoryMovementReferenceType InventoryMovementReferenceType
	Valid                          bool // Valid is true if InventoryMovementReferenceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryMovementReferenceType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryMovementReferenceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryMovementReferenceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryMovementReferenceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryMovementReferenceType), nil
}

type InventoryMovementType string

const (
	InventoryMovementTypeADJUSTMENT  InventoryMovementType = "ADJUSTMENT"
	InventoryMovementTypeINBOUND     InventoryMovementType = "INBOUND"
	InventoryMovementTypeOUTBOUND    InventoryMovementType = "OUTBOUND"
	InventoryMovementTypeRESERVATION InventoryMovementType = "RESERVATION"
)

func (e *InventoryMovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InventoryMovementType(s)
	case string:
		*e = InventoryMovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for InventoryMovementType: %T", src)
	}
	return nil
}

type NullInventoryMovementType struct {
	InventoryMovementType InventoryMovementType
	Valid                 bool // Valid is true if InventoryMovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInventoryMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.InventoryMovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InventoryMovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInventoryMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InventoryMovementType), nil
}

type ItemType string

const (
	ItemTypeASSET   ItemType = "ASSET"
	ItemTypePRODUCT ItemType = "PRODUCT"
)

func (e *ItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemType(s)
	case string:
		*e = ItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemType: %T", src)
	}
	return nil
}

type NullItemType struct {
	ItemType ItemType
	Valid    bool // Valid is true if ItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemType) Scan(value interface{}) error {
	if value == nil {
		ns.ItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemType), nil
}

type Account struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Country   Country
	Deleted   bool
	Nickname  sql.NullString
	OwnerID   uuid.NullUUID
}

type AccountsUsers struct {
	AccountID uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ApiKey struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ExpiresAt      sql.NullTime
	Name           string
	Note           sql.NullString
	RedactedSecret string
	Secret         string
	AccountID      uuid.UUID
}

type Group struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Description   sql.NullString
	Name          string
	AccountID     uuid.UUID
	ParentGroupID uuid.NullUUID
}

type Inventory struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	InStock   int32
	Orderable sql.NullInt32
	Reserved  sql.NullInt32
	AccountID uuid.UUID
}

type InventoryMovement struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Quantity    int32
	Type        InventoryMovementType
	AccountID   uuid.UUID
	InventoryID uuid.UUID
	ItemID      uuid.UUID
}

type InventoryMovementReference struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Value               string
	Type                InventoryMovementReferenceType
	AccountID           uuid.UUID
	InventoryMovementID uuid.UUID
}

type Item struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Active        bool
	Description   sql.NullString
	HasVariants   bool
	Name          string
	PriceAmount   sql.NullInt32
	PriceCurrency NullCurrency
	Type          ItemType
	Variant       bool
	AccountID     uuid.UUID
	GroupID       uuid.NullUUID
	InventoryID   uuid.NullUUID
	ParentItemID  uuid.NullUUID
}

type ItemIdentifier struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Ean       sql.NullString
	Gtin      sql.NullString
	Isbn      sql.NullString
	Jan       sql.NullString
	Mpn       sql.NullString
	Nsn       sql.NullString
	Upc       sql.NullString
	Qr        sql.NullString
	Sku       sql.NullString
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type ItemVariantAttribute struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	AccountID uuid.UUID
	ItemID    uuid.UUID
}

type ItemVariantAttributeOption struct {
	ID                     uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
	Name                   string
	AccountID              uuid.UUID
	ItemVariantAttributeID uuid.UUID
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedPassword string
	Name           sql.NullString
}
